
[core]
name: run_gun_boat
class: CustomUnitMetadata
price: 300
maxHp: 140
mass: 3000

displayText:草鱼级
displayDescription:-掠袭艇 \n-只能攻击空中和地面单位 \n-移动速度快
overrideAndReplace: gunBoat

tags:water,light,gunBoat

techLevel: 1

buildSpeed: 0.005
availableInDemo: true

radius: 9
displayRadius: 9

isBio: false

#builtFrom_1_name: airFactory
#builtFrom_1_pos:  3


[graphics]

total_frames: 1
image:        run_gun_boat.png
image_wreak:  run_gun_boat_dead.png
image_turret: NONE
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

splastEffect:true

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1



[attack]
turretRotateWithBody: false

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

showRangeUIGuide:false
turretSize: 0
#turretTurnSpeed: 2

aimOffsetSpread:0.4


maxAttackRange: 150
shootDelay: 30

isFixedFiring: false


[turret_1]
invisible: true
x: 0
y: 0
idleDir:0

projectile: 1


turnSpeed: 15
turnSpeedAcceleration: 15


shoot_sound:gun_fire
shoot_sound_vol:0.2
shoot_flame:small
shoot_light:#FFEEEE00




#recoilOffset: -2
#recoilOutTime: 10
#recoilReturnTime: 14






[projectile_1]
directDamage: 12
life: 70
speed: 10
frame: 5
drawSize: 0.7
#instant:true


[movement]
movementType: water


reverseSpeedPercentage: 0.6

moveSpeed: 1.51
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06

maxTurnSpeed: 3
turnAcceleration: 0.4


moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181





