
[core]
name: heavy_aa_ship

displayText:烟火级
displayDescription:-重巡洋舰 \n-只能攻击空中和地面单位 \n-在海岸线周围建造部分建筑 \n-能修复单位
class: CustomUnitMetadata
price: 14000
maxHp: 2100
mass: 40000

techLevel: 1
buildSpeed: 0.00035
availableInDemo: true

radius: 34
#displayRadius: 11

transportSlotsNeeded: 3

isBio: false
#softCollisionOnAll: 3

tags: heavyAAShip,heavy,water


builtFrom_1_name: seaFactory
builtFrom_1_pos:  5

maxShield: 4000

overrideAndReplace:heavyAAShip


canRepairBuildings: true
canRepairUnits : true



canReclaimResources: true

autoRepair: true

nanoRange: 220

nanoRepairSpeed: 0.4
nanoBuildSpeed: 1

[canBuild_4]
name: landFactory, airFactory
pos:  4
tech: 1


[canBuild_6]
name: seaFactory
pos:  6
tech: 1

[canBuild_7]
name: fabricator
pos:  9

[canBuild_8]
name: repairBay
pos:  8

[canBuild_5]
name: laserDefence
pos:  7

[canBuild_10]
name: turret
pos:  3.1

[canBuild_11]
name: antiAirTurret
pos:  3.2



[canBuild_16]
name: extractor
pos:  2.9
tech: 1

[canBuild_17]
name: reclaim
pos:  -1

[graphics]
total_frames: 1

image:        run_heavy_aa_ship.png
image_wreak:  run_heavy_aa_ship_dead.png
image_turret: anti_air_top_flakgun.png
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

image_shadow: SHADOW:run_heavy_aa_ship.png
shadowOffsetX:3
shadowOffsetY:3


splastEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 7	
turretTurnSpeed: 1.8



maxAttackRange: 330
shootDelay: 140

turretMultiTargeting: true

[turret_nanoTurret]
x: 0
y: 32
#invisible: true


turnSpeed: 4
size: 8

image: SHARED:nano_turret.png

canShoot: false

isMainNanoTurret: true

[turret_main]
x: 0
y: 19
size:22
image:turret_top_artillery.png

shoot_sound:large_gun_fire1
shoot_sound_vol:0.5
shoot_flame:large
shoot_light:#FFEECCCC

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
projectile: main


recoilOffset: -2.5
recoilOutTime: 2
recoilReturnTime: 40

idleDir:0
idleDirReversing: -145

[turret_flak]
#pivot point
x: 0
y: -2
canShoot: false

canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turnSpeed: 2.8
turnSpeedAcceleration: 0.3



recoilOffset: -2.5
recoilOutTime: 2
recoilReturnTime: 40


idleSpin: 0.8
#idleSweepAngle:60
#idleSweepDelay:140
#idleSweepSpeed:0.3
#shouldResetTurret: false



[turret_2]
#left flak cannon
x: 6
y: 6
attachedTo: flak
slave: true
invisible: true
warmup: 0

projectile: aa
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

shoot_sound:large_gun_fire2
shoot_sound_vol:0.3
shoot_flame:large
shoot_light:#FFEECCCC

#image: SHARED:debug_marker.png

[turret_3]
#right flak cannon
x: -6
y: 6

copyFrom: 2
linkDelayWithTurret:2
warmup: 25


[projectile_main]
#main turret projectile

life: 150
speed: 4
largeHitEffect: true
frame: 2
targetGround: true
areaDamage: 350
areaRadius: 65

lightColor: #ffe92b
lightSize: 0.6

[projectile_aa]
#directDamage: 60
life: 240
speed: 20
#targetSpeed: 6

trailEffect: true
trailEffectRate: 0.75
largeHitEffect: true
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 0

areaDamage: 70
areaRadius: 60

autoTargetingOnDeadTarget: true

lightColor: #ffff00
lightSize: 0.4

[movement]
movementType: WATER
moveSpeed: 0.7
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.03

reverseSpeedPercentage:1

maxTurnSpeed: 1.2
turnAcceleration: 0.05


