
[core]
name: run_missile_ship
class: CustomUnitMetadata
price: 500
maxHp: 120
mass: 5000

displayText:侏儒级
displayDescription:-游击艇 \n-发射导弹 \n-只能攻击空中和地面单位 \n-射程较远且拥有强大的单发伤害但射速慢
overrideAndReplace: missileShip



techLevel: 1

buildSpeed: 0.0015
availableInDemo: true

radius: 13

tags: missileShip,light,water

[graphics]

total_frames: 1
image:         run_missile_ship.png
image_wreak:  run_missile_ship_dead.png
image_turret: NONE
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

splastEffect:true

#AUTO
image_shadow: AUTO
shadowOffsetX:3
shadowOffsetY:3



[attack]
turretRotateWithBody: false

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

showRangeUIGuide:false
turretSize: 0
#turretTurnSpeed: 2

aimOffsetSpread:0.4

turretMultiTargeting: true

maxAttackRange: 250
shootDelay: 170

isFixedFiring: false


[turret_1]
x: 0
y: 0
shoot_sound:missile_fire
projectile: 1


[projectile_1]
directDamage: 90
life: 210
speed: 1.8
ballistic:true
ballistic_height:35
ballistic_delaymove_height:25
autoTargetingOnDeadTarget:true
color:#FFD700
drawSize: 2
trailEffect: true


[movement]
movementType: water


reverseSpeedPercentage: 1

moveSpeed: 1.2
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06

maxTurnSpeed: 2
turnAcceleration: 0.4


moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181





