[core]
name:run_barrack
displayText:兵营
displayDescription:-招聘快速便宜的步兵单位 \n-招聘廉价的防暴单位
price:600
maxHp:660
mass:9000
footprint:-1,-2,0,0
constructionFootprint:-1,-2,0,0
buildingToFootprintOffsetY:-16
buildingToFootprintOffsetX:0
techLevel:1
buildSpeed:16.6s
radius:17
isBio:false
isBuilding:true
numBitsOnDeath:20
builtFrom_1_name:builder
builtFrom_1_pos:3.8
builtFrom_3_name:combatEngineer
builtFrom_3_pos:3.8
builtFrom_5_name:experimentalSpider
builtFrom_5_pos:0.4
canBuild_1_name:setRally
canBuild_1_pos:-1
#canBuild_2_name:engineer
#canBuild_2_pos:0.1
canBuild_3_name:run_infantrys,run_anti_air_gun
canBuild_3_pos:0.2
canBuild_3_isLocked:if numberOfUnitsInNeutralTeam(withinRange=1000,withTag='galaxy',greaterThan=0)
canBuild_3_isLockedMessage:无法建造
canBuild_4_name:run_motorized_soldier
canBuild_4_pos:0.6
canBuild_4_isLocked:if numberOfUnitsInNeutralTeam(withinRange=1000,withTag='galaxy',greaterThan=0)
canBuild_4_isLockedMessage:无法建造
[graphics]
total_frames:1
image:run_barrack.png
image_back:run_barrack_back.png
image_wreak:run_barrack_dead.png
image_shadow:NONE
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:NONE
moveSpeed:0
maxTurnSpeed:0
[ai]
buildPriority:0.50
noneInBaseExtraPriority:0.80
maxEachBase:1
