
[core]
name: nautilusSubmarine
class: CustomUnitMetadata
showInEditor:true

#displayText: Nautilus
#displayDescription: -Heavily armed and armored \n -Can attack ships \n -Can surface and walk on land \n -Can attack land and air when surfaced

displayLocaleKey: nautilusSubmarine

overrideAndReplace:nautilusSubmarine

tags:water,experiemental,nautilusSubmarine

price: 18000
maxHp: 4000
mass: 30000
selfRegenRate:0.1

techLevel: 1
experimental: true
buildSpeed: 0.0003
availableInDemo: false

radius: 36
isBio: false


fogOfWarSightRange:24


builtFrom_1_name: seaFactory
builtFrom_1_pos:  6

nanoFactorySpeed:2
canBuild_1_name: lightSub, gunBoat, missileShip, builderShip

canBuild_2_name: hoverTank


energyMax: 6
energyRegen: 0.01
energyNeedsToRechargeToFull: true

maxTransportingUnits: 3
transportUnitsRequireMovementType: WATER, HOVER, OVER_CLIFF_WATER
transportUnitsCanUnloadUnits: false
#transportUnitsCanUnloadUnits: if self.isOverLiquid()
transportUnitsRequireTag: nonexistent

transportUnitsKeepBuiltUnits: true


exit_x:0
exit_y:30

exit_dirOffset:0
exit_moveAwayAmount:110
exit_heightOffset: 0


[hiddenAction_trigger_onLand]
autoTrigger: if not self.overWater()
convertTo: nautilusSubmarineLand




[action_surface]
convertTo: nautilusSubmarineSurface
#isActive: if not self.isOverwater
displayType: action
price:  0
text: Surface
description: -Surface unit
buildSpeed: 1
whenBuilding_cannotMove: true
pos:0.6
highPriorityQueue: true

spawnEffects: CUSTOM:displacement_ripples, CUSTOM:ripples*3, CUSTOM:largeRipples

iconExtraImage: SHARED:icon_upgrade.png
iconExtraColor: #FFFFFF

[action_dive]
isVisible: false

convertTo: nautilusSubmarine
isActive: if self.isOverwater
displayType: action
price:  0
text: Dive
description: -Dive unit underwater

#buildSpeed effected by nanoFactorySpeed:2
buildSpeed: 4.5s
whenBuilding_cannotMove: true
pos:0.6
highPriorityQueue: true

spawnEffects: CUSTOM:displacement_ripples, CUSTOM:ripples*3, CUSTOM:largeRipples

iconExtraImage: SHARED:icon_downgrade.png
iconExtraColor: #FFFFFF

[action_launchScoutBot]
id:launchScoutBot

isVisible: false
pos:0.8
fireTurretXAtGround: botTurret
fireTurretXAtGround_onlyOverPassableTileOf: HOVER


#price: credits=250, energy=1
price: credits=250
text: Launch scout bot
description: -Launch a scout bot to the target location
displayType: action
buildSpeed: 3.5s

addActionCooldownTime: 30s

iconExtraImage: SHARED:icon_attack_point.png
iconExtraColor: #FFFFFF

unitShownInUI: robotCrab


allowMultipleInQueue: false
whenBuilding_cannotMove: true






[action_buildAntiNuke]
id:buildAntiNuke

price:  6000
text: i:gui.actions.buildAntiNuke
description:i:gui.actions.buildAntiNukeNautilus.description
displayType: NONE

#don't want a speed up from nanoFactorySpeed
buildSpeed: ${ 0.0005 / core.nanoFactorySpeed }
pos: 0.2
isActive:if self.ammoIncludingQueued(lessThan=4)
addResources: ammo=1
isLocked: if not game.nukesEnabled()
isLockedMessage: i:gui.actions.nukesDisabled

iconImage: SHARED:icon_build.png


[action_showAntiNukeCount]

#infoOnly: true
addResources: ammo=1
price:  ammo=1
text: i:gui.actions.antiNukeCount
description:i:gui.actions.antiNukeCount.description
buildSpeed: 0s
pos: 0.1
displayRemainingStockpile: true
displayType: infoOnlyStockpile


isActive:false
isVisible: if self.ammo(greaterThan=0)

iconImage: SHARED:icon_nuke_stockpile.png

[action_showAntiNukeCountEmpty]
#infoOnly: true

text: i:gui.actions.antiNukeCountEmpty
description:i:gui.actions.antiNukeCount.descriptionEmpty
buildSpeed: 0s
pos: 0.1
#displayRemainingStockpile: true
displayType: infoOnlyStockpile

isActive:false
isVisible: if self.ammo(lessThan=1)

iconImage: SHARED:icon_nuke_stockpile.png






[graphics]
drawLayer: experimentals
total_frames: 1


image:        body.png
image_wreak:  body_dead.png
image_turret: foot.png


image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits:false


turretSize: 20
turretTurnSpeed: 1.8


maxAttackRange: 240
shootDelay: 300

[turret_1]
#gun turret (not in use)
x: 0
y: 27
idleDir:0
invisible: true
canShoot: false


[turret_2]
#missile turret
x: 10
y: 22
idleDir:0

invisible: true

shoot_flame:shockwave
shoot_light:#FFEECCCC

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false


projectile: 2
size: 1
turnSpeed: 40

energyUsage: 1


[turret_3]
#back turret
copyFrom: 2

x: -10
y: 22
idleDir:0
warmup:20
projectile: 2
linkDelayWithTurret:2


[turret_4]
#back turret
copyFrom: 2

x: -10
y: 14
idleDir:0
warmup:40
projectile: 2
linkDelayWithTurret:2


[turret_5]
#back turret
copyFrom: 2

x: 10
y: 14
idleDir:0
warmup:60
projectile: 2
linkDelayWithTurret:2


[turret_6]
#back turret
copyFrom: 2

x: 10
y: 4
idleDir:0
warmup:80
projectile: 2
linkDelayWithTurret:2


[turret_7]
#back turret
copyFrom: 2

x: -10
y: 4
idleDir:0
warmup:100
projectile: 2
linkDelayWithTurret:2


[turret_botTurret]
#bot turret
x: 10
y: 22
canShoot:false
idleDir:0

invisible: true

shoot_sound:missile_fire
shoot_sound_vol:1
shoot_light:#FFEECCCC

projectile: scoutBotProjectile
size: 1

turnSpeed: 40
shoot_flame:shockwave

limitingRange: 500



[turret_antiNuke]
#anti-nuke turret
x: 7
y: 20
canShoot:false


idleDir:0
invisible: true

projectile: antiNukeMissile
interceptProjectiles_withTags: nuke
interceptProjectiles_andTargetingGroundUnderDistance: 500
interceptProjectiles_andUnderDistance: 1100
interceptProjectiles_andOverHeight:50

shoot_sound:nuke_launch
shoot_sound_vol:0.15
shoot_light:#FFEECCCC

size: 1

turnSpeed: 40

resourceUsage: ammo=1

shoot_flame:shockwave, smoke
#shoot_flame:custom:nukeLaunch
#onShoot_playAnimation: fireNuke



[projectile_scoutBotProjectile]
life: 0
spawnProjectilesOnEndOfLife: scoutBotProjectileSplit(offsetDir=15), scoutBotProjectileSplit(offsetDir=-180)
directDamage: 0

[projectile_scoutBotProjectileSplit]
#Scout bot

directDamage: 123
drawSize: 0.9
spawnUnit:robotCrab


life: 90
speed: 0.3
targetSpeed: 6
targetSpeedAcceleration: 0.05


trailEffect: true
largeHitEffect: true

ballistic: true
ballistic_delaymove_height:20
ballistic_height: 50
#initialUnguidedSpeedHeight: 1

frame: 9

targetGround: true

deflectionPower:-1

lightColor: #FFEEEE00
lightSize: 1

wobbleAmplitude: 1
wobbleFrequency: 60
targetGroundSpread: 5

turnSpeed:4
spawnProjectilesOnEndOfLife: scoutBotProjectileSplitFastTurn

[projectile_scoutBotProjectileSplitFastTurn]
@copyFromSection: projectile_scoutBotProjectileSplit

spawnProjectilesOnEndOfLife: NONE
life: 150
turnSpeed:9

speed: 2

[projectile_2]
#torpedo
directDamage: 50


life: 250
speed: 0.15
targetSpeed: 1.2
drawSize: 1
color: #1E1E96
lightColor:#ffffff
trailEffect: true
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:40
ballistic_height: -2

autoTargetingOnDeadTarget: true



[projectile_3]
#missile
directDamage: 35
drawSize: 0.8
life: 240
speed: 0.3
targetSpeed: 6
trailEffect: true
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:40
ballistic_height: 50
frame: 4

areaDamage: 180
areaRadius: 55

autoTargetingOnDeadTarget: true


[projectile_antiNukeMissile]
#anti-nuke
directDamage: 600

life: 99999
speed: 0.2
targetSpeed: 6.5
targetSpeedAcceleration:0.05

trailEffect: true
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
frame: 10
#shadowFrame:1

drawType:0

targetGround: true
areaDamage: 100
areaRadius: 60

areaExpandTime:75

deflectionPower:-1


lightColor: #FFEEEE00
lightSize: 1


alwaysVisibleInFog: true



[movement]
movementType: WATER
moveSpeed: 0.45
moveAccelerationSpeed: 0.015
moveDecelerationSpeed: 0.05

reverseSpeedPercentage:0.6
targetHeight:-8
targetHeightDrift: 0.1
maxTurnSpeed: 0.8
turnAcceleration: 0.05
heightChangeRate: 0.005


[ai]
useAsTransport: false


#wave_normal_128.png



[effect_displacement_ripples]

#displacement type ignored if postprocessing is not enabled
drawType: displacement

image: SHARED:ripple_normal_128.png
life: 60
fadeOut: true
fadeInTime: 3

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.3
scaleTo: 1.8
alpha: 0.1
drawUnderUnits:false

dirOffsetRandom: 180
dirSpeed: 1
delayedStartTimer: 5


[effect_ripples]
image: SHARED:ripple.png
life: 60
lifeRandom: 20

fadeOut: true
fadeInTime: 3

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.6
drawUnderUnits:false

dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5

delayedStartTimer: 5


[effect_largeRipples]
image: SHARED:ripple.png
life: 40

fadeOut: true
fadeInTime: 3

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 1.9
alpha: 0.7
drawUnderUnits:false

dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5

delayedStartTimer: 5

