[core]
name:cpc_houyi_tank
displayText:后羿
displayDescription:-反重型狙击悬浮坦克（停下时攻击） \n-远距离打击 \n-伤害高，但开火间隔十分长 \n-可以同时攻击空中和地面单位 \n-移动时只能攻击空中单位
class:CustomUnitMetadata
price:1400
maxHp:300
mass:6000
techLevel:1
buildSpeed:27.7s
tags:default
radius:15
softCollisionOnAll:0
autoTriggerCooldownTime:0.10s
[graphics]
icon_zoomed_out:ROOT:res/drawable/hovertank_sniper_icon.png
total_frames:1
teamColorsOnTurret:true
image:cpc_houyi_tank.png
image_wreak:NONE
image_turret:cpc_houyi_tank_turret.png
turretImageScale:0.90
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
splastEffect:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:18
turretTurnSpeed:3
isFixedFiring: true

maxAttackRange:310
shootDelay:450
[turret_1]
x:0
y:0
barrelX:-3.5
barrelOffsetX_onOddShots: 5.5
projectile:1
canAttackLandUnits:if not self.isMoving()

turnSpeedAcceleration: 1.0

shoot_sound:cannon_firing
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEEEEEE

recoilOffset: -2
recoilOutTime: 9
recoilReturnTime: 18

[projectile_1]
life: 150
speed: 3.5

frame: 2
color: #bebe50

directDamage:0
areaDamage:210
areaRadius:65
areaHitAirAndLandAtSameTime:true

largeHitEffect: true
targetGround: true

lightColor: #ffe92b
lightSize: 0.4

targetGroundSpread: 30
initialUnguidedSpeedHeight: 1.2
#gravity:0.18
lightCastOnGround: true
[movement]
movementType:HOVER
moveSpeed:0.6
moveAccelerationSpeed:0.025
moveDecelerationSpeed:0.05
maxTurnSpeed:2.4
turnAcceleration:0.15
moveIgnoringBody:true
targetHeightDrift:2.5
targetHeight:5
