[core]
name:run_tank
displayText:谢尔曼
displayDescription:-中型掠袭/突击坦克 \n-可以同时攻击空中与地面单位 \n-只能使用导弹防空且防空能力十分弱 \n-导弹为直射火力
class:CustomUnitMetadata
overrideAndReplace:tank
price:400
maxHp:210
mass:4500
techLevel:1
buildSpeed:8.3s
#availableInDemo: true
radius:14
displayRadius:14
isBio:false
softCollisionOnAll:0
[graphics]
total_frames:3
image:run_tank.png
image_wreak:run_tank_dead.png
image_turret:run_tank_turret.png
imageScale:0.8
scaleTurretImagesTo:14
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start:0
animation_moving_end:2
animation_moving_speed:1
dustEffect:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:20
turretTurnSpeed:4
maxAttackRange:140
shootDelay:48
[turret_1]
x:0
y:0
canShoot:false
[turret_2]
x:0
y:0
slave:true
attachedTo:1
projectile:1
invisible:true
canAttackFlyingUnits:false
turnSpeedAcceleration:1.0
shoot_sound:tank_firing
shoot_sound_vol:1
shoot_flame:small
shoot_light:#FFEECCCC
recoilOffset:-2
[turret_3]
x:0
y:-15
slave:true
attachedTo:1
warmup:48
barrelX:6
barrelOffsetX_onOddShots:-12
invisible:true
projectile:2
canAttackFlyingUnits:true
turnSpeedAcceleration:1.0
shoot_sound:missile_fire
shoot_sound_vol:1
recoilOffset:-2
[projectile_1]
directDamage:25
life:60
speed:5
frame:1
drawSize:1
[projectile_2]
directDamage:0
areaDamage:10
areaRadius:20
areaHitAirAndLandAtSameTime:true
areaDamageNoFalloff:true
explodeOnEndOfLife:true
life:60
speed:0.1
turnSpeed:0
turnSpeedWhenNear:0
targetSpeedAcceleration:0.07
targetSpeed:6
frame:4
drawSize:1
#Direct Shoot Effect
trailEffect:true
largeHitEffect:true
autoTargetingOnDeadTarget:true
trailEffectRate:10
explodeEffect:smallExplosion
color: #ffffff
[movement]
movementType:LAND
moveSpeed:1
moveAccelerationSpeed:0.03
moveDecelerationSpeed:0.12
maxTurnSpeed:4.1
turnAcceleration:0.07
moveSlidingMode:false
moveIgnoringBody:false
